[package]
name = "kai-book"
version = "0.1.0"
description = "A versatile system tray contact book for freelancers"
authors = ["Raj"]
edition = "2021"

[lib]
name = "kai_book_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "macos-private-api"] }
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
tokio = { version = "1", features = ["time"] }
